## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [1]:
import numpy as np
# setting up vectors
a = np.arange(5,11,1)
print(a)

b = np.arange(15,21,1)
print(b)

[ 5  6  7  8  9 10]
[15 16 17 18 19 20]


In [2]:
# outer product w/o numpy
outer = [[a[i]*b[j] for j in range(len(b))] for i in range(len(a))]
print('Outer Product: ', outer)
# 6x6 matrix

Outer Product:  [[75, 80, 85, 90, 95, 100], [90, 96, 102, 108, 114, 120], [105, 112, 119, 126, 133, 140], [120, 128, 136, 144, 152, 160], [135, 144, 153, 162, 171, 180], [150, 160, 170, 180, 190, 200]]


In [5]:
# check with numpy function
outer = np.outer(a,b)
print(outer)

[[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]


6

In [9]:
# calculate trace without numpy
print(len(outer))
trace = []
for i in range(len(outer)):
    trace.append(outer[i,i])
print('Trace = ',sum(trace))

6
Trace =  805


In [10]:
# check with numpy
trace = np.trace(outer)
print('Trace = ', trace)

Trace =  805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [11]:
# setup matrices of random numbers
A = np.random.randn(4,3)
print(A)
B = np.random.randn(3,4)
print(B)

[[-0.06957501 -0.20286335 -2.08474378]
 [-0.33832993 -1.08348985  0.17838482]
 [-0.13866876 -0.73624955 -0.47084729]
 [-0.4767243   0.84749633  0.42340506]]
[[ 0.25343975  1.71411022 -0.02914146  0.02522155]
 [ 0.45296825 -0.0914227  -1.33079914 -2.05596246]
 [-0.25835091  0.10715911 -0.02056765  1.1942295 ]]


In [12]:
q = A[0,:]*B[:,0]
print(q)
sum(q)
# so you can use this kind of thing to multiply a row of A and a column of B, then sum terms

[-0.01763307 -0.09189065  0.53859546]


0.42907173017571554

In [13]:
# here's the for loop version
C1 = np.zeros( (4,4) )
# we know C1 will be 4x4
for i in range(len(A[:,0])):
    for j in range(len(B[0,:])):
        x = A[i,:]*B[:,j]
        C1[i,j] = sum(x)
print(C1)

[[ 0.42907173 -0.32411221  0.31487616 -2.0743379 ]
 [-0.62261863 -0.46176365  1.44809784  2.43211368]
 [-0.24699802 -0.2208392   0.9935255   0.94790427]
 [ 0.15368096 -0.8492667  -1.1226634  -1.24880155]]


In [14]:
# now for a list comprehension version...
C2 = np.zeros( (4,4) )
C2 = [[sum(A[i,:]*B[:,j]) for j in range(len(B[0,:]))] for i in range(len(A[:,0]))]
# if you loop over i first, the output is the transpose of what you want
print(C2)

[[0.42907173017571554, -0.3241122097815208, 0.3148761564862357, -2.074337898345175], [-0.6226186326633149, -0.4617636497587696, 1.4480978384056666, 2.4321136802731416], [-0.24699801883994216, -0.2208392000872114, 0.9935255028646088, 0.9479042722283771], [0.15368095647247174, -0.8492666970471938, -1.1226633983923031, -1.248801554816374]]


In [15]:
# and the numpy version to check everything with
C = np.matmul(A,B)
print(C)

[[ 0.42907173 -0.32411221  0.31487616 -2.0743379 ]
 [-0.62261863 -0.46176365  1.44809784  2.43211368]
 [-0.24699802 -0.2208392   0.9935255   0.94790427]
 [ 0.15368096 -0.8492667  -1.1226634  -1.24880155]]


In [94]:
tale = C[[0,1]][:,[0,1]]
print(tale)
# okay, grabbed the upper quad

[[ 0.72557117 -0.09436308]
 [ 1.83826304 -0.50673878]]


In [97]:
# replace all of the diagonal entries with 0
for i in range(len(C)):
    C[i,i] = 0
print(C)

[[ 0.         -0.09436308  1.79835015 -0.83456042]
 [ 1.83826304  0.          1.15642942 -1.55013815]
 [-2.06260334  0.44118598  0.          1.68875637]
 [-3.1395533   1.00508732  1.09211366  0.        ]]
