## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [6]:
import numpy as np
a = np.arange(5,11,1)
print(a)

b = np.arange(15,21,1)
print(b)

[ 5  6  7  8  9 10]
[15 16 17 18 19 20]


In [29]:
outer = [[a[i]*b[j] for j in range(len(b))] for i in range(len(a))]
print('Outer Product: ', outer)
# 6x6 matrix

outer = np.outer(a,b)

Outer Product:  [[75, 80, 85, 90, 95, 100], [90, 96, 102, 108, 114, 120], [105, 112, 119, 126, 133, 140], [120, 128, 136, 144, 152, 160], [135, 144, 153, 162, 171, 180], [150, 160, 170, 180, 190, 200]]


In [41]:
trace = []
for i in range(len(outer)):
    trace.append(outer[i,i])
print('Trace = ',sum(trace))

Trace =  805


In [36]:
trace = np.trace(outer)
print(trace)

805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [54]:
A = np.random.randn(4,3)
print(A)
B = np.random.randn(3,4)
print(B)

[[-1.09884539  0.83740701  0.4258072 ]
 [-1.69924737  0.89736099 -0.21209531]
 [ 1.55616345  0.42877271 -0.44224183]
 [ 1.5670672   0.89726198  0.97723534]]
[[-1.3218366   0.33793804 -0.61404393  1.04925242]
 [-0.58574407  0.1563096   0.51175522  0.29776127]
 [-0.55522003  0.34307503  1.632343    0.16218228]]


In [76]:
q = A[0,:]*B[:,0]
print(q)
sum(q)
# so you can use this kind of thing to multiply a row of A and a column of B, then sum terms

[ 1.45249405 -0.49050619 -0.23641668]


0.7255711704779405

In [89]:
# here's the for loop version
C1 = np.zeros( (4,4) )
# we know C1 will be 4x4
for i in range(len(A[:,0])):
    for j in range(len(B[0,:])):
        x = A[i,:]*B[:,j]
        C1[i,j] = sum(x)
print(C1)

[[ 0.72557117 -0.09436308  1.79835015 -0.83456042]
 [ 1.83826304 -0.50673878  1.15642942 -1.55013815]
 [-2.06260334  0.44118598 -1.45801642  1.68875637]
 [-3.1395533   1.00508732  1.09211366  2.06990916]]


In [88]:
# now for a list comprehension version...
C2 = np.zeros( (4,4) )
C2 = [[sum(A[i,:]*B[:,j]) for j in range(len(B[0,:]))] for i in range(len(A[:,0]))]
# if you loop over i first, the output is the transpose of what you want
print(C2)

[[0.7255711704779405, -0.09436307987446746, 1.7983501528967858, -0.8345604200570091], [1.8382630383123153, -0.5067387841398068, 1.1564294212733648, -1.5501381544666528], [-2.0626033416982956, 0.4411859843761628, -1.458016418970005, 1.688756372815107], [-3.1395532956460475, 1.0050873224070787, 1.0921136609752131, 2.069909164064269]]


In [87]:
# and the numpy version to check everything with
C = np.matmul(A,B)
print(C)

[[ 0.72557117 -0.09436308  1.79835015 -0.83456042]
 [ 1.83826304 -0.50673878  1.15642942 -1.55013815]
 [-2.06260334  0.44118598 -1.45801642  1.68875637]
 [-3.1395533   1.00508732  1.09211366  2.06990916]]


In [94]:
tale = C[[0,1]][:,[0,1]]
print(tale)
# okay, grabbed the upper quad

[[ 0.72557117 -0.09436308]
 [ 1.83826304 -0.50673878]]


In [97]:
# replace all of the diagonal entries with 0
for i in range(len(C)):
    C[i,i] = 0
print(C)

[[ 0.         -0.09436308  1.79835015 -0.83456042]
 [ 1.83826304  0.          1.15642942 -1.55013815]
 [-2.06260334  0.44118598  0.          1.68875637]
 [-3.1395533   1.00508732  1.09211366  0.        ]]
